name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vendorito:
    runs-on: ubuntu-latest
    steps:
      - uses: Neosperience/vendorito@v0.1.1
        with:
          source: minio/minio
          target: quay.io/hamcha/minio-mirror
          credentials: ${{ secrets.QUAYCREDENTIALS }}
