name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vendorito:
    runs-on: ubuntu-latest
    steps:
      - uses: Neosperience/vendorito@4ade10b4b1596e12bda45ad12f9e738d45ed0b0e
        with:
          source: minio/minio
          target: quay.io/hamcha/minio-mirror
          credentials: ${{ secrets.QUAYCREDENTIALS }}
